import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

const financeCoreBuildPatch = () => ({
  name: 'saveflow-finance-core-build-patch',
  enforce: 'pre',
  transform(code, id) {
    if (!id.endsWith('/src/App.jsx')) return null
    let s = code
    s = s.replace("import './ReferenceTheme.css'", "import './ReferenceTheme.css'\nimport { RATES, toMdl, fromMdl, localDateKey, localMonthKey, calculateHealth } from './lib/financeCore'")
    s = s.replace("\nconst RATES = { MDL: 1, EUR: 19.5, USD: 17.5 }\n", "\n")
    s = s.replace("const todayKey = () => new Date().toISOString().slice(0, 10)", "const todayKey = () => localDateKey()")
    s = s.replace("const mdlToDisplay = (v, c) => Number(v || 0) / (RATES[c] || 1)", "const mdlToDisplay = (v, c) => fromMdl(v, c)")
    s = s.replace("const displayToMdl = (v, c) => Number(v || 0) * (RATES[c] || 1)", "const displayToMdl = (v, c) => toMdl(v, c)")
    s = s.replace('const currentMonthKey = todayKey().slice(0, 7)', 'const currentMonthKey = localMonthKey()')
    s = s.replace('const availableBalance = Math.max(0, totalIncome - totalExpenses - totalSaved)', 'const availableBalance = totalIncome - totalExpenses - totalSaved')
    s = s.replace(/const financialHealth = useMemo\(\(\) => \{\n    const income = Math\.max\(profileMonthlyIncome, totalIncome, 1\)\n    const saveRate = Math\.min\(1, totalSaved \/ income\)\n    const spendingRate = Math\.min\(1, monthTotal \/ income\)\n    const budget = weeklyBudget > 0 \? Math\.max\(0, 1 - weekTotal \/ weeklyBudget\) : \.5\n    return Math\.round\(Math\.min\(100, Math\.max\(0, 35\*saveRate \+ 35\*\(1-spendingRate\) \+ 20\*budget \+ 10\)\)\)\n  \}, \[profileMonthlyIncome,totalIncome,totalSaved,monthTotal,weeklyBudget,weekTotal\]\)/, `const financialHealth = useMemo(() => calculateHealth({\n    income: Math.max(profileMonthlyIncome, totalIncome, 0),\n    expenses: monthTotal,\n    savings: totalSaved,\n    weeklySpent: weekTotal,\n    weeklyBudget,\n    emergencyMonths: 0,\n  }), [profileMonthlyIncome, totalIncome, monthTotal, totalSaved, weekTotal, weeklyBudget])`)

    s = s.replace("    if (e) { setError(e.message); return }\n    setAmount(''); setNote(''); setModal(null); await load()", `    if (e) { setError(e.message); return }\n    if (paymentMethod === 'cash' || paymentMethod === 'card') {\n      const nextCash = paymentMethod === 'cash' ? Number(data.cash || 0) - mdl : Number(data.cash || 0)\n      const nextCard = paymentMethod === 'card' ? Number(data.card || 0) - mdl : Number(data.card || 0)\n      const { error: balanceError } = await supabase.from('daily_balances').upsert({ user_id: session.user.id, balance_date: todayKey(), cash_amount: nextCash, card_amount: nextCard }, { onConflict: 'user_id,balance_date' })\n      if (balanceError) { setError(balanceError.message); return }\n    }\n    setAmount(''); setNote(''); setModal(null); await load()`)

    s = s.replace("      user_id: session.user.id, type: 'income', amount: incomeMdl, category: 'Income', note: incomeSource || 'Venit',\n      payment_method: null, transaction_date: todayKey(),", "      user_id: session.user.id, type: 'income', amount: incomeMdl, category: 'Income', note: incomeSource || 'Venit',\n      payment_method: paymentMethod, transaction_date: todayKey(),")
    s = s.replace("    if (save > 0) {", `    if (paymentMethod === 'cash' || paymentMethod === 'card') {\n      const netIncomeMdl = incomeMdl - saveMdl\n      const nextCash = paymentMethod === 'cash' ? Number(data.cash || 0) + netIncomeMdl : Number(data.cash || 0)\n      const nextCard = paymentMethod === 'card' ? Number(data.card || 0) + netIncomeMdl : Number(data.card || 0)\n      const { error: balanceError } = await supabase.from('daily_balances').upsert({ user_id: session.user.id, balance_date: todayKey(), cash_amount: nextCash, card_amount: nextCard }, { onConflict: 'user_id,balance_date' })\n      if (balanceError) { setError(balanceError.message); return }\n    }\n    if (save > 0) {`)
    s = s.replace("<label>{ui('Sursă','Source','Источник')}</label><input value={incomeSource} onChange={e=>setIncomeSource(e.target.value)} placeholder=\"Salariu\"/>", "<label>{ui('Sursă','Source','Источник')}</label><input value={incomeSource} onChange={e=>setIncomeSource(e.target.value)} placeholder=\"Salariu\"/><label>{ui('Unde ai primit banii?','Where did you receive the money?','Куда поступили деньги?')}</label><div className=\"payment-choice\"><button className={paymentMethod==='cash'?'selected':''} onClick={()=>setPaymentMethod('cash')}>💵 {t.cash}</button><button className={paymentMethod==='card'?'selected':''} onClick={()=>setPaymentMethod('card')}>💳 {t.card}</button></div>")

    s = s.replace("monthlyIncome: profile?.monthly_income ? String(profile.monthly_income) : '', rent: profile?.rent ? String(profile.rent) : '',", "monthlyIncome: profile?.monthly_income ? String(mdlToDisplay(profile.monthly_income, profile?.currency || 'MDL')) : '', rent: profile?.rent ? String(mdlToDisplay(profile.rent, profile?.currency || 'MDL')) : '',")
    s = s.replace("bills: profile?.bills ? String(profile.bills) : '', food: profile?.food ? String(profile.food) : '',", "bills: profile?.bills ? String(mdlToDisplay(profile.bills, profile?.currency || 'MDL')) : '', food: profile?.food ? String(mdlToDisplay(profile.food, profile?.currency || 'MDL')) : '',")
    s = s.replace("transport: profile?.transport ? String(profile.transport) : '', subscriptions: profile?.subscriptions ? String(profile.subscriptions) : '',", "transport: profile?.transport ? String(mdlToDisplay(profile.transport, profile?.currency || 'MDL')) : '', subscriptions: profile?.subscriptions ? String(mdlToDisplay(profile.subscriptions, profile?.currency || 'MDL')) : '',")
    s = s.replace("other: profile?.other_costs ? String(profile.other_costs) : '', savingsTarget:", "other: profile?.other_costs ? String(mdlToDisplay(profile.other_costs, profile?.currency || 'MDL')) : '', savingsTarget:")
    s = s.replace("monthly_income:income,rent:Number(onboardingData.rent||0),bills:Number(onboardingData.bills||0),food:Number(onboardingData.food||0),transport:Number(onboardingData.transport||0),subscriptions:Number(onboardingData.subscriptions||0),other_costs:Number(onboardingData.other||0),savings_target_percent:targetRate,onboarding_completed:true,monthly_budget:Math.max(1,income-monthlyCosts),weekly_budget:recommendedWeekly,", "monthly_income:displayToMdl(income,currency),rent:displayToMdl(Number(onboardingData.rent||0),currency),bills:displayToMdl(Number(onboardingData.bills||0),currency),food:displayToMdl(Number(onboardingData.food||0),currency),transport:displayToMdl(Number(onboardingData.transport||0),currency),subscriptions:displayToMdl(Number(onboardingData.subscriptions||0),currency),other_costs:displayToMdl(Number(onboardingData.other||0),currency),savings_target_percent:targetRate,onboarding_completed:true,monthly_budget:displayToMdl(Math.max(1,income-monthlyCosts),currency),weekly_budget:displayToMdl(recommendedWeekly,currency),")
    s = s.replace("monthly_income: income, rent: Number(onboardingData.rent || 0), bills: Number(onboardingData.bills || 0),\n      food: Number(onboardingData.food || 0), transport: Number(onboardingData.transport || 0),\n      subscriptions: Number(onboardingData.subscriptions || 0), other_costs: Number(onboardingData.other || 0),\n      savings_target_percent: targetRate, monthly_budget: Math.max(1, income - monthlyCosts), weekly_budget: recommendedWeekly,", "monthly_income: displayToMdl(income, currency), rent: displayToMdl(Number(onboardingData.rent || 0), currency), bills: displayToMdl(Number(onboardingData.bills || 0), currency),\n      food: displayToMdl(Number(onboardingData.food || 0), currency), transport: displayToMdl(Number(onboardingData.transport || 0), currency),\n      subscriptions: displayToMdl(Number(onboardingData.subscriptions || 0), currency), other_costs: displayToMdl(Number(onboardingData.other || 0), currency),\n      savings_target_percent: targetRate, monthly_budget: displayToMdl(Math.max(1, income - monthlyCosts), currency), weekly_budget: displayToMdl(recommendedWeekly, currency),")

    s = s.replace("    await supabase.from('savings_goals').update({ current_amount: Number(goal.current_amount || 0) + actual }).eq('id', selectedGoalId).eq('user_id', session.user.id)\n    setSavingAmount('');", `    await supabase.from('savings_goals').update({ current_amount: Number(goal.current_amount || 0) + actual }).eq('id', selectedGoalId).eq('user_id', session.user.id)\n    if (actual > 0 && (paymentMethod === 'cash' || paymentMethod === 'card')) {\n      const nextCash = paymentMethod === 'cash' ? Number(data.cash || 0) - actual : Number(data.cash || 0)\n      const nextCard = paymentMethod === 'card' ? Number(data.card || 0) - actual : Number(data.card || 0)\n      const { error: balanceError } = await supabase.from('daily_balances').upsert({ user_id: session.user.id, balance_date: todayKey(), cash_amount: nextCash, card_amount: nextCard }, { onConflict: 'user_id,balance_date' })\n      if (balanceError) { setError(balanceError.message); return }\n    }\n    setSavingAmount('');`)
    s = s.replace("    if (e) { setError(e.message); return }\n    setSavingAmount(''); setModal(null); await load()\n  }\n\n  const createGoal", `    if (e) { setError(e.message); return }\n    if (mdl > 0 && (paymentMethod === 'cash' || paymentMethod === 'card')) {\n      const nextCash = paymentMethod === 'cash' ? Number(data.cash || 0) - mdl : Number(data.cash || 0)\n      const nextCard = paymentMethod === 'card' ? Number(data.card || 0) - mdl : Number(data.card || 0)\n      const { error: balanceError } = await supabase.from('daily_balances').upsert({ user_id: session.user.id, balance_date: todayKey(), cash_amount: nextCash, card_amount: nextCard }, { onConflict: 'user_id,balance_date' })\n      if (balanceError) { setError(balanceError.message); return }\n    }\n    setSavingAmount(''); setModal(null); await load()\n  }\n\n  const createGoal`)

    s = s.replace("<p className=\"muted\">{ui('Economiile sunt separate de cheltuielile Cash/Card.','Savings are separate from Cash/Card expenses.','Накопления отделены от расходов наличными/картой.')}</p>", "<label>{ui('Din ce sold economisești?','Which balance are you saving from?','Из какого баланса откладывать?')}</label><div className=\"payment-choice\"><button className={paymentMethod==='cash'?'selected':''} onClick={()=>setPaymentMethod('cash')}>💵 {t.cash}</button><button className={paymentMethod==='card'?'selected':''} onClick={()=>setPaymentMethod('card')}>💳 {t.card}</button></div><p className=\"muted\">{ui('Economiile se mută din soldul ales și rămân în fondul de economii.','Savings are moved from the selected balance into savings.','Накопления переводятся из выбранного баланса в сбережения.')}</p>")
    s = s.replace("<p className=\"muted\">{ui('SaveFlow recalculează automat progresul și timpul rămas.','SaveFlow automatically recalculates progress and time remaining.','SaveFlow автоматически пересчитает прогресс и оставшееся время.')}</p>", "<label>{ui('Din ce sold economisești?','Which balance are you saving from?','Из какого баланса откладывать?')}</label><div className=\"payment-choice\"><button className={paymentMethod==='cash'?'selected':''} onClick={()=>setPaymentMethod('cash')}>💵 {t.cash}</button><button className={paymentMethod==='card'?'selected':''} onClick={()=>setPaymentMethod('card')}>💳 {t.card}</button></div><p className=\"muted\">{ui('SaveFlow recalculează automat progresul și timpul rămas.','SaveFlow automatically recalculates progress and time remaining.','SaveFlow автоматически пересчитает прогресс и оставшееся время.')}</p>")

    // Changing currency must preserve the real MDL values already entered in the plan form.
    s = s.replace("const savePreferences = async (nextLang = language, nextCurrency = currency) => {\n    const { error: e } = await supabase.from('profiles').update({ language: nextLang, currency: nextCurrency, updated_at: new Date().toISOString() }).eq('id', session.user.id)\n    if (e) setError(e.message); else { setLanguage(nextLang); setCurrency(nextCurrency) }\n  }", `const savePreferences = async (nextLang = language, nextCurrency = currency) => {\n    const oldCurrency = currency\n    const convertPlan = value => { const n = Number(value || 0); return n ? String(fromMdl(toMdl(n, oldCurrency), nextCurrency)) : '' }\n    const { error: e } = await supabase.from('profiles').update({ language: nextLang, currency: nextCurrency, updated_at: new Date().toISOString() }).eq('id', session.user.id)\n    if (e) setError(e.message); else {\n      if (nextCurrency !== oldCurrency) setOnboardingData(d => ({ ...d, monthlyIncome: convertPlan(d.monthlyIncome), rent: convertPlan(d.rent), bills: convertPlan(d.bills), food: convertPlan(d.food), transport: convertPlan(d.transport), subscriptions: convertPlan(d.subscriptions), other: convertPlan(d.other) }))\n      setLanguage(nextLang); setCurrency(nextCurrency)\n    }\n  }`)
    return { code: s, map: null }
  },
})

export default defineConfig({
  plugins: [financeCoreBuildPatch(), react()],
})
