import { supabase } from './lib/supabase'
import { calculateAffordability, calculateMonthlyMetrics, calculateEmergencyMonths, calculateSpendingPace, localDateKey, localMonthKey, toMdl } from './lib/financeCore'

const STYLE_ID='saveflow-v4-tools-style', PANEL_ID='saveflow-v4-tools'
const css=`#${PANEL_ID}{margin:14px 0 90px}.sf4-card{background:#fff;border:1px solid rgba(13,67,48,.08);border-radius:22px;padding:18px;box-shadow:0 12px 35px rgba(14,55,43,.07)}.sf4-head{display:flex;justify-content:space-between;margin-bottom:14px}.sf4-head h3{margin:3px 0;font-size:20px;color:#12382c}.sf4-head span{font-size:11px;letter-spacing:.12em;font-weight:800;color:#6d857b}.sf4-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.sf4-btn{border:1px solid #e4ece8;background:#f7faf9;border-radius:15px;padding:12px;text-align:left;font:inherit;color:#183d31;cursor:pointer}.sf4-btn b{display:block;font-size:13px;margin-bottom:4px}.sf4-btn small{display:block;color:#71847d;font-size:11px}.sf4-kpi{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid #edf2ef}.sf4-kpi span{color:#71847d;font-size:12px}.sf4-kpi b{color:#163c30;text-align:right}.sf4-alert{padding:12px 14px;border-radius:14px;background:#fff8e7;margin-top:10px;color:#654d13;font-size:12px;line-height:1.45}.sf4-good{background:#edf9f2;color:#155b3d}.sf4-warn{background:#fff0ef;color:#8a3128}.sf4-modal{position:fixed;inset:0;background:rgba(8,25,20,.42);display:flex;align-items:center;justify-content:center;padding:18px;z-index:9999}.sf4-modal-box{width:min(520px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:24px;padding:20px}.sf4-close{float:right;border:0;background:#eef4f1;border-radius:10px;width:34px;height:34px;font-size:20px}.sf4-input{width:100%;box-sizing:border-box;padding:12px;border:1px solid #dbe6e1;border-radius:12px;margin:6px 0 12px;font:inherit}.sf4-primary{width:100%;border:0;background:#19d98b;color:#073b28;border-radius:13px;padding:12px;font-weight:800}.sf4-month{display:flex;gap:8px;align-items:center;margin-bottom:14px}.sf4-month button{border:0;background:#eef4f1;border-radius:9px;width:34px;height:34px}.sf4-month strong{flex:1;text-align:center;color:#173b30}.sf4-rec{padding:12px 0;border-bottom:1px solid #edf2ef;display:flex;justify-content:space-between;gap:10px}.sf4-rec small{display:block;color:#74867f;margin-top:3px}.sf4-danger{border:0;background:#fff0ef;color:#9b352c;border-radius:9px;padding:7px 9px}@media(max-width:520px){.sf4-grid{grid-template-columns:1fr}.sf4-card{padding:15px}.sf4-modal{padding:10px}.sf4-modal-box{padding:16px}}
`
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))
const money=(v,c='MDL')=>new Intl.NumberFormat('ro-MD',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(v||0))
const txDate=x=>String(x?.transaction_date||x?.created_at||'').slice(0,10)
const monthTitle=k=>new Intl.DateTimeFormat('ro-MD',{month:'long',year:'numeric'}).format(new Date(`${k}-01T12:00:00`))
const shift=(k,n)=>{const d=new Date(`${k}-01T12:00:00`);d.setMonth(d.getMonth()+n);return localMonthKey(d)}
const ex=c=>c.tx.filter(x=>x.type==='expense'), inc=c=>c.tx.filter(x=>x.type==='income')

async function context(){
 const {data:{session}}=await supabase.auth.getSession();if(!session)return null;const uid=session.user.id
 const [t,p,s,r]=await Promise.all([
  supabase.from('transactions').select('id,type,amount,category,note,payment_method,transaction_date,created_at').eq('user_id',uid).order('created_at',{ascending:false}),
  supabase.from('profiles').select('*').eq('id',uid).maybeSingle(),
  supabase.from('savings_contributions').select('id,amount,goal_id,created_at,contribution_date').eq('user_id',uid),
  supabase.from('recurring_expenses').select('*').eq('user_id',uid).eq('active',true).order('next_date',{ascending:true})
 ])
 return {uid,tx:t.data||[],profile:p.data||{},savings:s.data||[],recurring:r.data||[],recurringError:r.error}
}
function modal(html){document.querySelector('.sf4-modal')?.remove();const w=document.createElement('div');w.className='sf4-modal';w.innerHTML=`<div class="sf4-modal-box">${html}</div>`;w.onclick=e=>{if(e.target===w)w.remove()};document.body.appendChild(w);return w}
function mount(){if(document.getElementById(PANEL_ID))return;const app=document.querySelector('.app');if(!app)return;if(!document.getElementById(STYLE_ID)){const s=document.createElement('style');s.id=STYLE_ID;s.textContent=css;document.head.appendChild(s)}const el=document.createElement('section');el.id=PANEL_ID;el.innerHTML=`<div class="sf4-card"><div class="sf4-head"><div><span>SMART TOOLS</span><h3>SaveFlow Plus</h3></div><span>V4</span></div><div class="sf4-grid"><button class="sf4-btn" data-tool="month"><b>📊 Luna mea</b><small>Raport și comparație</small></button><button class="sf4-btn" data-tool="today"><b>📅 Azi</b><small>Buget zilnic</small></button><button class="sf4-btn" data-tool="alerts"><b>🔔 Smart Alerts</b><small>Riscuri și limite</small></button><button class="sf4-btn" data-tool="streak"><b>🔥 No-Spend Streak</b><small>Zile fără cheltuieli</small></button><button class="sf4-btn" data-tool="afford"><b>🧠 Îți permiți?</b><small>Impactul cumpărăturii</small></button><button class="sf4-btn" data-tool="recurring"><b>🔁 Recurente</b><small>Chirie și abonamente</small></button><button class="sf4-btn" data-tool="csv"><b>⬇️ Export CSV</b><small>Tranzacțiile tale</small></button></div></div>`;const nav=app.querySelector('.bottom-nav');nav?app.insertBefore(el,nav):app.appendChild(el);el.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>run(b.dataset.tool))}
async function run(tool){const c=await context();if(!c)return;const cur=c.profile.currency||'MDL';({month:()=>month(c,cur),today:()=>today(c,cur),alerts:()=>alerts(c,cur),streak:()=>streak(c),afford:()=>afford(c,cur),recurring:()=>recurring(c,cur),csv:()=>csv(c)}[tool]||(()=>{}))()}
function today(c,cur){const today=localDateKey(),spent=ex(c).filter(x=>txDate(x)===today).reduce((a,x)=>a+Number(x.amount),0),mk=localMonthKey(),ms=ex(c).filter(x=>txDate(x).slice(0,7)===mk).reduce((a,x)=>a+Number(x.amount),0),budget=Number(c.profile.monthly_budget||0),d=new Date(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),daily=budget?Math.max(0,(budget-ms)/Math.max(1,days-d.getDate()+1)):0;modal(`<button class="sf4-close" onclick="this.closest('.sf4-modal').remove()">×</button><h3>📅 Bugetul de azi</h3><div class="sf4-kpi"><span>Cheltuit azi</span><b>${money(spent,cur)}</b></div><div class="sf4-kpi"><span>Recomandat azi</span><b>${budget?money(daily,cur):'—'}</b></div><div class="sf4-kpi"><span>Cheltuit luna aceasta</span><b>${money(ms,cur)}</b></div>${budget?`<div class="sf4-alert ${spent<=daily?'sf4-good':'sf4-warn'}">${spent<=daily?'✓ Ești în ritm.':'⚠️ Ai depășit ritmul recomandat.'}</div>`:'<div class="sf4-alert">Setează bugetul lunar pentru recomandări precise.</div>'}`)}
function month(c,cur){let k=localMonthKey();const render=()=>{const m=calculateMonthlyMetrics({transactions:c.tx,savings:c.savings,month:k}),p=calculateMonthlyMetrics({transactions:c.tx,savings:c.savings,month:shift(k,-1)}),delta=p.expenses?Math.round((m.expenses-p.expenses)/p.expenses*100):null,essential=['rent','bills','food','transport','subscriptions','other_costs'].reduce((s,x)=>s+Number(c.profile[x]||0),0),em=calculateEmergencyMonths({savings:c.savings.reduce((s,x)=>s+Number(x.amount),0),monthlyEssentialCosts:essential}),days=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0).getDate(),pace=calculateSpendingPace({spent:m.expenses,daysElapsed:k===localMonthKey()?new Date().getDate():days,monthDays:days,budget:Number(c.profile.monthly_budget||0)});return `<button class="sf4-close" onclick="this.closest('.sf4-modal').remove()">×</button><div class="sf4-month"><button data-prev>‹</button><strong>${esc(monthTitle(k))}</strong><button data-next>›</button></div><div class="sf4-kpi"><span>Venituri</span><b>${money(m.income,cur)}</b></div><div class="sf4-kpi"><span>Cheltuieli</span><b>${money(m.expenses,cur)}${delta!==null?` (${delta>0?'+':''}${delta}% vs anterior)`:''}</b></div><div class="sf4-kpi"><span>Economii</span><b>${money(m.saved,cur)} · ${Math.round(m.savingsRate)}%</b></div><div class="sf4-kpi"><span>Schimbare sold</span><b>${money(m.balanceChange,cur)}</b></div><div class="sf4-kpi"><span>Fond de urgență</span><b>${em.toFixed(1)} luni</b></div>${pace.ratio?`<div class="sf4-alert ${pace.ratio<=1?'sf4-good':'sf4-warn'}">Ritmul actual proiectează ${money(pace.projected,cur)} cheltuieli.</div>`:''}`} ;const w=modal(render());const bind=()=>{w.querySelector('[data-prev]').onclick=()=>{k=shift(k,-1);w.querySelector('.sf4-modal-box').innerHTML=render();bind()};w.querySelector('[data-next]').onclick=()=>{k=shift(k,1);w.querySelector('.sf4-modal-box').innerHTML=render();bind()}};bind()}
function alerts(c,cur){const mk=localMonthKey(),e=ex(c),spent=e.filter(x=>txDate(x).slice(0,7)===mk).reduce((s,x)=>s+Number(x.amount),0),budget=Number(c.profile.monthly_budget||0),now=new Date(),ws=new Date(now);ws.setDate(now.getDate()-6);const week=e.filter(x=>new Date(x.created_at||x.transaction_date)>=ws).reduce((s,x)=>s+Number(x.amount),0),weekly=Number(c.profile.weekly_budget||0),a=[];if(budget&&spent>=budget*.8)a.push(`Ai folosit ${Math.round(spent/budget*100)}% din bugetul lunar.`);if(weekly&&week>=weekly*.8)a.push(`Ai folosit ${Math.round(week/weekly*100)}% din bugetul ultimelor 7 zile.`);const by={};e.filter(x=>txDate(x).slice(0,7)===mk).forEach(x=>by[x.category||'Other']=(by[x.category||'Other']||0)+Number(x.amount));const top=Object.entries(by).sort((a,b)=>b[1]-a[1])[0];if(top&&spent&&top[1]/spent>.4)a.push(`${top[0]} reprezintă ${Math.round(top[1]/spent*100)}% din cheltuielile lunii.`);modal(`<button class="sf4-close" onclick="this.closest('.sf4-modal').remove()">×</button><h3>🔔 Smart Alerts</h3>${a.length?a.map(x=>`<div class="sf4-alert sf4-warn">⚠️ ${esc(x)}</div>`).join(''):'<div class="sf4-alert sf4-good">✓ Nu există alerte importante acum.</div>'}`)}
function streak(c){const days=new Set(ex(c).map(txDate));let cur=0,d=new Date();d.setHours(12,0,0,0);while(cur<365&&!days.has(localDateKey(d))){cur++;d.setDate(d.getDate()-1)}let best=0,run=0;for(let i=364;i>=0;i--){const x=new Date();x.setHours(12,0,0,0);x.setDate(x.getDate()-i);if(!days.has(localDateKey(x)))run++;else{best=Math.max(best,run);run=0}}best=Math.max(best,run);modal(`<button class="sf4-close" onclick="this.closest('.sf4-modal').remove()">×</button><h3>🔥 No-Spend Streak</h3><div class="sf4-kpi"><span>Streak curent</span><b>${cur} zile</b></div><div class="sf4-kpi"><span>Record 365 zile</span><b>${best} zile</b></div>`)}
function afford(c,cur){const balance=inc(c).reduce((s,x)=>s+Number(x.amount),0)-ex(c).reduce((s,x)=>s+Number(x.amount),0)-c.savings.reduce((s,x)=>s+Number(x.amount),0),mk=localMonthKey(),ms=ex(c).filter(x=>txDate(x).slice(0,7)===mk).reduce((s,x)=>s+Number(x.amount),0),daily=ms/Math.max(1,new Date().getDate());modal(`<button class="sf4-close" onclick="this.closest('.sf4-modal').remove()">×</button><h3>🧠 Îți permiți?</h3><div class="sf4-kpi"><span>Sold estimat</span><b>${money(balance,cur)}</b></div><label>Sumă (${cur})</label><input class="sf4-input" id="sf4-p" type="number" min="0" placeholder="800"><button class="sf4-primary" id="sf4-check">Verifică</button><div id="sf4-r"></div>`);document.getElementById('sf4-check').onclick=()=>{const r=calculateAffordability({balance,purchase:Number(document.getElementById('sf4-p').value||0),safeDailySpend:daily,safetyDays:3});document.getElementById('sf4-r').innerHTML=r.purchase?`<div class="sf4-alert ${r.affordable?'sf4-good':'sf4-warn'}">${r.affordable?'✓ Pare sustenabilă':'⚠️ Mai bine amână'}<br>După cumpărare: <b>${money(r.after,cur)}</b></div>`:''}}
async function recurring(c,cur){if(c.recurringError){modal(`<button class="sf4-close" onclick="this.closest('.sf4-modal').remove()">×</button><h3>🔁 Recurente</h3><div class="sf4-alert sf4-warn">Tabela nu este disponibilă. Aplică migration-ul V4 în Supabase.</div>`);return}const w=modal(`<button class="sf4-close" onclick="this.closest('.sf4-modal').remove()">×</button><h3>🔁 Cheltuieli recurente</h3>${c.recurring.length?c.recurring.map(r=>`<div class="sf4-rec"><div><b>${esc(r.name)}</b><small>${money(r.amount,cur)} · ${esc(r.frequency)} · ${esc(r.next_date)}</small></div><button class="sf4-danger" data-del="${esc(r.id)}">Șterge</button></div>`).join(''):'<div class="sf4-alert">Nu ai cheltuieli recurente.</div>'}<hr><input class="sf4-input" id="r-name" placeholder="Nume"><input class="sf4-input" id="r-amount" type="number" min="0" placeholder="Sumă ${cur}"><input class="sf4-input" id="r-date" type="date" value="${localDateKey()}"><select class="sf4-input" id="r-freq"><option value="monthly">Lunar</option><option value="weekly">Săptămânal</option><option value="yearly">Anual</option></select><button class="sf4-primary" id="r-add">Adaugă</button>`);w.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{await supabase.from('recurring_expenses').delete().eq('id',b.dataset.del).eq('user_id',c.uid);recurring(await context(),cur)});w.querySelector('#r-add').onclick=async()=>{const name=w.querySelector('#r-name').value.trim(),amount=Number(w.querySelector('#r-amount').value),next_date=w.querySelector('#r-date').value,frequency=w.querySelector('#r-freq').value;if(!name||amount<=0||!next_date)return;const {error}=await supabase.from('recurring_expenses').insert({user_id:c.uid,name,amount:toMdl(amount,cur),category:'Other',payment_method:'card',frequency,next_date,active:true});if(error)alert(error.message);else recurring(await context(),cur)}}
function csv(c){const rows=c.tx,head=['Date','Type','Amount_MDL','Category','Payment_Method','Note'],lines=[head,...rows.map(x=>[txDate(x),x.type,x.amount,x.category||'',x.payment_method||'',x.note||''])].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')),blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`saveflow-${localDateKey()}.csv`;a.click();URL.revokeObjectURL(url)}
let bootTimer;const boot=()=>{clearTimeout(bootTimer);bootTimer=setTimeout(()=>{try{mount()}catch(e){console.warn('SaveFlow tools',e)}},300)};boot();new MutationObserver(boot).observe(document.body,{childList:true,subtree:true})
